* API to maintain a lab journal

The goal of the API is to create, setup and schedule exploratory research. In a
lab with a pre-existing annotated data-sets, exploratory research is experiments
running training and testing software models with a sample of the data-set
generated by the application. A typical example is a researcher has an
experiment in the form of a application, he(she) begins by pre-registering the
experiment by defining the characteristics of the corpus and the source of the
experiment. The application will generate a set of training and testing
data-sets, schedule a job to run the test and collect the results. The research
can track the progress between different versions of the experiment application
and different data-sets.

The API documents and automates the configuration and scheduling of the training
and testing of models.

** Concepts

*** Personas

There's two types of personas a account could have:

- researcher :: The persona has the permission to create and manage experiments
- worker :: The persona has the permission to launch experiments according to
  the specifications

*** Glossary

- exploratory research :: The basis of the research is the specification of the
  data. The provenance is key in the research, therefore the =source= =version=
  and =specification= identifies a specific population with a corpus.

  - data_repository :: A base uri where the data can be downloaded
  - version :: The assumption is that every change to the corpus is captured and
    tagged. The version tag can be either a date or a UUID.
  - specification :: The set of filters to apply onto the corpus. It's in the
    form of a map object (edn for now).


** The work-flow

*** Pre-registration the reseach

Initialization of the research in the system. The researcher enters the title,
hypothesis and the application repository.
